export * from './create-salary.controller';
export * from './update-salary.controller';
export * from './delete-salary.controller';
export * from './get-salaries.controller';
export * from './get-salary.controller';
export * from './salary-history/add-salary.controller';
export * from './salary-history/update-salary-history.controller';
export * from './salary-history/delete-salary-history.controller';
export * from './salary-history/get-provider-salary-history.controller';
export * from './salary-history/get-provider-one.controller';
export * from './salary-history/get-user-salary-history.controller';
export * from './salary-history/get-user-one.controller';
export * from  './salary-history/update-to-received.controller'